name: Deploy to Server
on:
  push:
    branches:
      - main  # Деплой при пуше в main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 17853 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 17853 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Переходим в директорию проекта
          cd /deploy/platonus-api-tracing-project
          
          # Используем правильный формат для передачи пароля в sudo
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S git fetch origin
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S git reset --hard origin/main
          
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          
          # Изменяем права с sudo
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S chmod +x ./auth-api/gradlew
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S chmod +x ./docs-api/gradlew
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S chmod +x ./api-gateway/gradlew
          
          # Запускаем gradlew с sudo
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S ./auth-api/gradlew -p ./auth-api build -x test
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S cp ./auth-api/build/libs/*.jar /app/auth-api/auth-api.jar
          
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S ./docs-api/gradlew -p ./docs-api build -x test
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S cp ./docs-api/build/libs/*.jar /app/docs-api/docs-api.jar
          
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S ./api-gateway/gradlew -p ./api-gateway build -x test
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S cp ./api-gateway/build/libs/*.jar /app/api-gateway/api-gateway.jar
          
          # Перезапускаем сервисы
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S supervisorctl reread
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S supervisorctl update
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S supervisorctl restart all
          EOF
