name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          cd front-end
          npm install
          npm run build
        shell: bash

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Verify SSH Connection
        run: |
          ssh -v -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -p ${{secrets.SSH_PORT}} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "whoami && pwd && uname -a"
        shell: bash

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -p ${{secrets.SSH_PORT}} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -x  # Enable debug mode
          
          # Navigate to project directory
          cd /deploy/platonus-api-tracing-project

          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S rm -rf ./auth-api/build
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S rm -rf ./docs-api/build
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S rm -rf ./api-gateway/build
          
          # Update project
          git fetch origin
          git reset --hard origin/main
          
          # Set Java environment
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          
          # Make gradlew executable
          chmod +x ./auth-api/gradlew
          chmod +x ./docs-api/gradlew
          chmod +x ./api-gateway/gradlew
          
          # Build and deploy services
          # Auth API
          ./auth-api/gradlew -p ./auth-api build -x test
          cp ./auth-api/build/libs/auth-api-0.0.1-SNAPSHOT.jar /app/auth-api/auth-api-0.0.1-SNAPSHOT.jar
          chmod 777 /app/auth-api/auth-api-0.0.1-SNAPSHOT.jar
          
          # Docs API
          ./docs-api/gradlew -p ./docs-api build -x test
          cp ./docs-api/build/libs/docs-api-0.0.1-SNAPSHOT.jar /app/docs-api/docs-api-0.0.1-SNAPSHOT.jar
          chmod 777 /app/docs-api/docs-api-0.0.1-SNAPSHOT.jar
          
          # API Gateway
          ./api-gateway/gradlew -p ./api-gateway build -x test
          cp ./api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway/api-gateway-0.0.1-SNAPSHOT.jar
          chmod 777 /app/api-gateway/api-gateway-0.0.1-SNAPSHOT.jar
          
          # Front-End
          rm -rf /app/main-ui/*
          cp -r ./front-end/dist/* /app/main-ui/
          chmod -R 755 /app/main-ui/
          
          # Restart services
          supervisorctl reread
          supervisorctl update
          supervisorctl restart all
          EOF
        shell: bash
  
