name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          cd front-end
          npm install
          npm run build
        shell: bash

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Verify SSH Connection
        run: |
          ssh -v -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -p ${{secrets.SSH_PORT}} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "whoami && pwd && uname -a"
        shell: bash

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -p ${{secrets.SSH_PORT}} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -x  # Enable debug mode
          
          # Функция для выполнения команд через sudo -S
          run_with_sudo() {
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S bash -c "$1"
          }

          # Установка максимальных прав для директории проекта
          run_with_sudo "chown -R $USER:$USER /deploy/platonus-api-tracing-project"
          run_with_sudo "chmod -R 777 /deploy/platonus-api-tracing-project"
          
          # Переход в директорию проекта
          cd /deploy/platonus-api-tracing-project
          
          # Очистка директорий сборки с максимальными правами
          run_with_sudo "rm -rf ./auth-api/build"
          run_with_sudo "rm -rf ./docs-api/build"
          run_with_sudo "rm -rf ./api-gateway/build"
          
          # Обновление проекта с максимальными правами
          run_with_sudo "git config --global --add safe.directory /deploy/platonus-api-tracing-project"
          run_with_sudo "git fetch origin"
          run_with_sudo "git reset --hard origin/main"
          
          # Установка переменных окружения
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          
          # Установка прав на gradlew
          run_with_sudo "chmod +x ./auth-api/gradlew"
          run_with_sudo "chmod +x ./docs-api/gradlew"
          run_with_sudo "chmod +x ./api-gateway/gradlew"
          
          # Сборка и деплой сервисов с максимальными правами
          
          # Auth API
          run_with_sudo "./auth-api/gradlew -p ./auth-api build -x test"
          run_with_sudo "cp ./auth-api/build/libs/auth-api-0.0.1-SNAPSHOT.jar /app/auth-api/auth-api-0.0.1-SNAPSHOT.jar"
          run_with_sudo "chmod 777 /app/auth-api/auth-api-0.0.1-SNAPSHOT.jar"
          
          # Docs API
          run_with_sudo "./docs-api/gradlew -p ./docs-api build -x test"
          run_with_sudo "cp ./docs-api/build/libs/docs-api-0.0.1-SNAPSHOT.jar /app/docs-api/docs-api-0.0.1-SNAPSHOT.jar"
          run_with_sudo "chmod 777 /app/docs-api/docs-api-0.0.1-SNAPSHOT.jar"
          
          # API Gateway
          run_with_sudo "./api-gateway/gradlew -p ./api-gateway build -x test"
          run_with_sudo "cp ./api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway/api-gateway-0.0.1-SNAPSHOT.jar"
          run_with_sudo "chmod 777 /app/api-gateway/api-gateway-0.0.1-SNAPSHOT.jar"
          
          # Front-End
          run_with_sudo "rm -rf /app/main-ui/*"
          run_with_sudo "cp -r ./front-end/dist/* /app/main-ui/"
          run_with_sudo "chmod -R 755 /app/main-ui/"
          
          # Перезапуск сервисов
          run_with_sudo "supervisorctl reread"
          run_with_sudo "supervisorctl update"
          run_with_sudo "supervisorctl restart all"
          EOF
        shell: bash
