name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug SSH Key Secrets
        run: |
          echo "SSH Host: ${{ secrets.SSH_HOST }}"
          echo "SSH Port: ${{ secrets.SSH_PORT }}"
          echo "SSH User: ${{ secrets.SSH_USER }}"
          # Маскируем приватный ключ
          echo "SSH Private Key length: ${#SSH_PRIVATE_KEY}"
        shell: bash
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Подробный вывод для диагностики
          ls -l ~/.ssh/id_rsa
          file ~/.ssh/id_rsa
          
          ssh-keyscan -p ${{secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh-keygen -l -f ~/.ssh/id_rsa || echo "SSH key generation check failed"
        shell: bash
      
      - name: Verify SSH Connection
        run: |
          # Максимально подробное подключение
          ssh -vvv -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -p ${{secrets.SSH_PORT}} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "whoami && pwd && uname -a"
        shell: bash
